# Generated by Django 3.2.3 on 2021-06-13 15:50

import booking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('persons', models.PositiveSmallIntegerField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('title_image', models.ImageField(upload_to=booking.models.title_image_path)),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
    ]
