# Generated by Django 3.2.3 on 2021-06-13 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ('name',)},
        ),
    ]
