# Generated by Django 3.2.3 on 2021-06-15 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('booking', '0003_house_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousePhoto',
            fields=[
                ('imagewiththumbnail_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.imagewiththumbnail')),
                ('index', models.PositiveIntegerField()),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='booking.house')),
            ],
            options={
                'unique_together': {('house', 'index')},
            },
            bases=('base.imagewiththumbnail',),
        ),
    ]
