# Generated by Django 3.2.3 on 2021-06-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_housephoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='housephoto',
            options={'ordering': ('index',)},
        ),
    ]
