# Generated by Django 3.2.3 on 2021-06-06 13:47

from django.db import migrations, models
import settings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(unique=True)),
                ('image', models.ImageField(upload_to=settings.models.carousel_picture_path)),
            ],
        ),
    ]
