# Generated by Django 3.2.3 on 2021-06-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselimage',
            options={'ordering': ('index',)},
        ),
    ]
