# Generated by Django 3.2.3 on 2021-06-15 16:44

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageWithThumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=base.models.image_path)),
                ('thumbnail', models.ImageField(upload_to='')),
            ],
        ),
    ]
